

INSERT INTO public.discount (discount, discount_type, name) VALUES (25.00, 'RATE_BASED', '%25');
INSERT INTO public.discount ( discount, discount_type, name) VALUES (50.00, 'AMOUNT_BASED', '50 dollar');

INSERT INTO public.category ( name) VALUES ('Termite Control');
INSERT INTO public.category ( name) VALUES ('Drywall & Acoustical (FED)');
INSERT INTO public.category ( name) VALUES ('Plumbing & Medical Gas');
INSERT INTO public.category ( name) VALUES ('Doors, Frames & Hardware');
INSERT INTO public.category ( name) VALUES ('Site Furnishings');
INSERT INTO public.category ( name) VALUES ('Soft Flooring and Base');
INSERT INTO public.category ( name) VALUES ('Overhead Doors');
INSERT INTO public.category ( name) VALUES ('Sitework & Site Utilities');
INSERT INTO public.category ( name) VALUES ('Drywall & Acoustical (FED)');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Glass & Glazing');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'Fire Protection');
INSERT INTO public.category ( name) VALUES ( 'Site Furnishings');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'Sitework & Site Utilities');
INSERT INTO public.category ( name) VALUES ( 'Marlite Panels (FED)');
INSERT INTO public.category ( name) VALUES ( 'Electrical');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Framing (Wood)');
INSERT INTO public.category ( name) VALUES ( 'Prefabricated Aluminum Metal Canopies');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Construction Clean and Final Clean');
INSERT INTO public.category ( name) VALUES ( 'Epoxy Flooring');
INSERT INTO public.category ( name) VALUES ( 'Overhead Doors');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Structural and Misc Steel (Fabrication)');
INSERT INTO public.category ( name) VALUES ( 'Drywall & Acoustical (MOB)');
INSERT INTO public.category ( name) VALUES ( 'Ornamental Railings');
INSERT INTO public.category ( name) VALUES ( 'Marlite Panels (FED)');
INSERT INTO public.category ( name) VALUES ( 'Termite Control');
INSERT INTO public.category ( name) VALUES ( 'Prefabricated Aluminum Metal Canopies');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Temp Fencing, Decorative Fencing and Gates');
INSERT INTO public.category ( name) VALUES ( 'Electrical and Fire Alarm');
INSERT INTO public.category ( name) VALUES ( 'Waterproofing & Caulking');
INSERT INTO public.category ( name) VALUES ( 'Wall Protection');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Temp Fencing, Decorative Fencing and Gates');
INSERT INTO public.category ( name) VALUES ( 'Granite Surfaces');
INSERT INTO public.category ( name) VALUES ( 'Fire Protection');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Plumbing & Medical Gas');
INSERT INTO public.category ( name) VALUES ( 'Asphalt Paving');
INSERT INTO public.category ( name) VALUES ( 'Drywall & Acoustical (MOB)');
INSERT INTO public.category ( name) VALUES ( 'HVAC');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');


INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('asturton0@list-manage.com', 'Anstice', 'Sturton', 'asturton0');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cmulqueeny1@networkadvertising.org', 'Cobby', 'Mulqueeny', 'cmulqueeny1');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bmaccaughey2@wufoo.com', 'Bell', 'MacCaughey', 'bmaccaughey2');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mbullivant3@behance.net', 'Maribelle', 'Bullivant', 'mbullivant3');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cpagitt4@slate.com', 'Casie', 'Pagitt', 'cpagitt4');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmonck5@webnode.com', 'Nance', 'Monck', 'nmonck5');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mokinneally6@zimbio.com', 'Moina', 'O''Kinneally', 'mokinneally6');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dpetchell7@oracle.com', 'Danny', 'Petchell', 'dpetchell7');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jrosenau8@dagondesign.com', 'Janela', 'Rosenau', 'jrosenau8');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ahammerich9@deliciousdays.com', 'Arley', 'Hammerich', 'ahammerich9');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tsicklinga@4shared.com', 'Tilda', 'Sickling', 'tsicklinga');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cbevissb@godaddy.com', 'Clyve', 'Beviss', 'cbevissb');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kfedorskic@berkeley.edu', 'Krystyna', 'Fedorski', 'kfedorskic');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mrummingsd@uiuc.edu', 'Marylynne', 'Rummings', 'mrummingsd');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('gknighte@bbb.org', 'Glennie', 'Knight', 'gknighte');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('lbynethf@infoseek.co.jp', 'Lutero', 'Byneth', 'lbynethf');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('aapplegarthg@nymag.com', 'Alma', 'Applegarth', 'aapplegarthg');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('twemmh@feedburner.com', 'Therese', 'Wemm', 'twemmh');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cantonognolii@sciencedaily.com', 'Cayla', 'Antonognoli', 'cantonognolii');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dcoplestonej@privacy.gov.au', 'Dodi', 'Coplestone', 'dcoplestonej');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ctimlink@dailymail.co.uk', 'Caralie', 'Timlin', 'ctimlink');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('apaverl@ox.ac.uk', 'Axe', 'Paver', 'apaverl');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('fbeminsterm@yahoo.co.jp', 'Flem', 'Beminster', 'fbeminsterm');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('aredwoodn@elegantthemes.com', 'Arne', 'Redwood', 'aredwoodn');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kkervino@miitbeian.gov.cn', 'Katina', 'Kervin', 'kkervino');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tcoolahanp@dailymotion.com', 'Tam', 'Coolahan', 'tcoolahanp');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kconrathq@indiegogo.com', 'Keelby', 'Conrath', 'kconrathq');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ephebyr@bloglines.com', 'Ernaline', 'Pheby', 'ephebyr');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mkasmans@ucsd.edu', 'Malissia', 'Kasman', 'mkasmans');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bcanett@typepad.com', 'Bryn', 'Canet', 'bcanett');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('minmettu@psu.edu', 'Marmaduke', 'Inmett', 'minmettu');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('obritneyv@bravesites.com', 'Olwen', 'Britney', 'obritneyv');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('omaww@free.fr', 'Olympie', 'Maw', 'omaww');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kmeesex@nhs.uk', 'Kerr', 'Meese', 'kmeesex');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmuldowneyy@ucla.edu', 'Nichol', 'Muldowney', 'nmuldowneyy');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('smacclintonz@spotify.com', 'Shae', 'MacClinton', 'smacclintonz');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('wjindacek10@weather.com', 'Wye', 'Jindacek', 'wjindacek10');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dmalone11@smh.com.au', 'Dix', 'Malone', 'dmalone11');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('rcaseri12@cbsnews.com', 'Rafaellle', 'Caseri', 'rcaseri12');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tcaddell13@spotify.com', 'Tricia', 'Caddell', 'tcaddell13');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dtyas14@canalblog.com', 'Dawn', 'Tyas', 'dtyas14');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cperrett15@domainmarket.com', 'Carole', 'Perrett', 'cperrett15');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tmcgloughlin16@pinterest.com', 'Tracee', 'McGloughlin', 'tmcgloughlin16');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jswaite17@icio.us', 'Janella', 'Swaite', 'jswaite17');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ajamson18@scribd.com', 'Aime', 'Jamson', 'ajamson18');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('atopliss19@flickr.com', 'Alis', 'Topliss', 'atopliss19');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('birdale1a@apache.org', 'Barbe', 'Irdale', 'birdale1a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('iaccomb1b@angelfire.com', 'Ingrim', 'Accomb', 'iaccomb1b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mpaudin1c@cnet.com', 'Murdoch', 'Paudin', 'mpaudin1c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('leustis1d@indiegogo.com', 'Laney', 'Eustis', 'leustis1d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jaishford1e@bing.com', 'Jamie', 'Aishford', 'jaishford1e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jcawkill1f@linkedin.com', 'Justis', 'Cawkill', 'jcawkill1f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tstute1g@bloglines.com', 'Trixy', 'Stute', 'tstute1g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('rgabbitus1h@deviantart.com', 'Rivy', 'Gabbitus', 'rgabbitus1h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('lwellstead1i@usatoday.com', 'Lutero', 'Wellstead', 'lwellstead1i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('crippon1j@barnesandnoble.com', 'Cherida', 'Rippon', 'crippon1j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cbeevers1k@google.com', 'Colleen', 'Beevers', 'cbeevers1k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('fdeverille1l@cloudflare.com', 'Fan', 'Deverille', 'fdeverille1l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ncamies1m@so-net.ne.jp', 'Nonie', 'Camies', 'ncamies1m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('drignoldes1n@oracle.com', 'Dilan', 'Rignoldes', 'drignoldes1n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('rmcroberts1o@theglobeandmail.com', 'Revkah', 'McRoberts', 'rmcroberts1o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('acourtier1p@google.pl', 'Amber', 'Courtier', 'acourtier1p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmerrison1q@ed.gov', 'Natividad', 'Merrison', 'nmerrison1q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ucapp1r@multiply.com', 'Uriah', 'Capp', 'ucapp1r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('swarrilow1s@fda.gov', 'Saundra', 'Warrilow', 'swarrilow1s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('gcastanyer1t@usnews.com', 'Goran', 'Castanyer', 'gcastanyer1t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('blewis1u@dot.gov', 'Bevin', 'Lewis', 'blewis1u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('joggers1v@webs.com', 'Jarid', 'Oggers', 'joggers1v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dlimpenny1w@dot.gov', 'Dani', 'Limpenny', 'dlimpenny1w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('hhully1x@patch.com', 'Hervey', 'Hully', 'hhully1x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('adoughton1y@earthlink.net', 'Anselm', 'Doughton', 'adoughton1y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('blynam1z@narod.ru', 'Brew', 'Lynam', 'blynam1z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('acrossley20@biglobe.ne.jp', 'Aurel', 'Crossley', 'acrossley20');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ntunuy21@vimeo.com', 'Nanete', 'Tunuy', 'ntunuy21');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('hthrustle22@taobao.com', 'Hamilton', 'Thrustle', 'hthrustle22');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('abeech23@cdbaby.com', 'Alanson', 'Beech', 'abeech23');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kfossick24@dell.com', 'Kiel', 'Fossick', 'kfossick24');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bragot25@wikimedia.org', 'Benita', 'Ragot', 'bragot25');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('elawie26@exblog.jp', 'Ezequiel', 'Lawie', 'elawie26');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bolufsen27@joomla.org', 'Bea', 'Olufsen', 'bolufsen27');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cduffet28@google.es', 'Cloris', 'Duffet', 'cduffet28');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('halliott29@feedburner.com', 'Hedwig', 'Alliott', 'halliott29');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('pfingleton2a@instagram.com', 'Pollyanna', 'Fingleton', 'pfingleton2a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bbramah2b@dell.com', 'Ber', 'Bramah', 'bbramah2b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('zpetry2c@google.com.hk', 'Zared', 'Petry', 'zpetry2c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nspurnier2d@woothemes.com', 'Noel', 'Spurnier', 'nspurnier2d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tellings2e@cloudflare.com', 'Toni', 'Ellings', 'tellings2e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tcrean2f@bluehost.com', 'Teodoor', 'Crean', 'tcrean2f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('fcordeau2g@dion.ne.jp', 'Farlie', 'Cordeau', 'fcordeau2g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('vsiemantel2h@usa.gov', 'Victoir', 'Siemantel', 'vsiemantel2h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bcolman2i@cpanel.net', 'Benetta', 'Colman', 'bcolman2i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jmccurrie2j@macromedia.com', 'Julina', 'McCurrie', 'jmccurrie2j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tdanielsen2k@auda.org.au', 'Terrel', 'Danielsen', 'tdanielsen2k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dclackson2l@posterous.com', 'Desmund', 'Clackson', 'dclackson2l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nbrigstock2m@devhub.com', 'Nora', 'Brigstock', 'nbrigstock2m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ljandel2n@seesaa.net', 'Linnie', 'Jandel', 'ljandel2n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmeeron2o@github.io', 'Nerissa', 'Meeron', 'nmeeron2o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('narbuckel2p@usgs.gov', 'Nettle', 'Arbuckel', 'narbuckel2p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jcockman2q@infoseek.co.jp', 'Jasmine', 'Cockman', 'jcockman2q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'eblaske2r@imgur.com', 'Englebert', 'Blaske', 'eblaske2r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cbaudouin2s@ask.com', 'Carmon', 'Baudouin', 'cbaudouin2s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'alaye2t@twitter.com', 'Alexine', 'Laye', 'alaye2t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mloverock2u@live.com', 'Maxy', 'Loverock', 'mloverock2u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'yelwin2v@goo.gl', 'Yance', 'Elwin', 'yelwin2v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bcleyne2w@uiuc.edu', 'Berrie', 'Cleyne', 'bcleyne2w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vmaddra2x@dot.gov', 'Vernor', 'Maddra', 'vmaddra2x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'amarquet2y@hexun.com', 'Ailsun', 'Marquet', 'amarquet2y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'csomner2z@huffingtonpost.com', 'Carissa', 'Somner', 'csomner2z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'blantiffe30@webs.com', 'Bertrando', 'Lantiffe', 'blantiffe30');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tkendrew31@wikipedia.org', 'Tory', 'Kendrew', 'tkendrew31');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bglason32@skyrock.com', 'Bonny', 'Glason', 'bglason32');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'imccluin33@fotki.com', 'Iggie', 'McCluin', 'imccluin33');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'khearty34@sohu.com', 'Korrie', 'Hearty', 'khearty34');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hgowanlock35@engadget.com', 'Horton', 'Gowanlock', 'hgowanlock35');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mhenricsson36@ebay.com', 'Miguelita', 'Henricsson', 'mhenricsson36');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kmugg37@uiuc.edu', 'Kristien', 'Mugg', 'kmugg37');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ggalliford38@virginia.edu', 'Ginnifer', 'Galliford', 'ggalliford38');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mtinman39@addthis.com', 'Morna', 'Tinman', 'mtinman39');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bwithringten3a@trellian.com', 'Benyamin', 'Withringten', 'bwithringten3a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'awison3b@wisc.edu', 'Asia', 'Wison', 'awison3b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pmalan3c@columbia.edu', 'Pincas', 'Malan', 'pmalan3c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rreye3d@jalbum.net', 'Redd', 'Reye', 'rreye3d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dpfeifer3e@reverbnation.com', 'Demetris', 'Pfeifer', 'dpfeifer3e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'melstone3f@vinaora.com', 'Minne', 'Elstone', 'melstone3f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sboxill3g@over-blog.com', 'Suzie', 'Boxill', 'sboxill3g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hduffil3h@europa.eu', 'Horacio', 'Duffil', 'hduffil3h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vscullard3i@msn.com', 'Verge', 'Scullard', 'vscullard3i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mquarrie3j@eepurl.com', 'Mick', 'Quarrie', 'mquarrie3j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ppettendrich3k@freewebs.com', 'Paco', 'Pettendrich', 'ppettendrich3k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lbridgen3l@1688.com', 'Lauritz', 'Bridgen', 'lbridgen3l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'docorrane3m@buzzfeed.com', 'Darlene', 'O''Corrane', 'docorrane3m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pspandley3n@cisco.com', 'Pail', 'Spandley', 'pspandley3n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'twithrington3o@mtv.com', 'Taddeusz', 'Withrington', 'twithrington3o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rmeekings3p@multiply.com', 'Rebekkah', 'Meekings', 'rmeekings3p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ebentsen3q@freewebs.com', 'Evie', 'Bentsen', 'ebentsen3q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'blockyer3r@amazon.com', 'Baxter', 'Lockyer', 'blockyer3r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tduckerin3s@smugmug.com', 'Tonie', 'Duckerin', 'tduckerin3s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'echater3t@twitter.com', 'Erma', 'Chater', 'echater3t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mscandrick3u@vinaora.com', 'Margo', 'Scandrick', 'mscandrick3u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dlempenny3v@webmd.com', 'Del', 'Lempenny', 'dlempenny3v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'blilion3w@so-net.ne.jp', 'Beatriz', 'Lilion', 'blilion3w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'zswyndley3x@amazon.co.jp', 'Zitella', 'Swyndley', 'zswyndley3x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ssaltman3y@purevolume.com', 'Sioux', 'Saltman', 'ssaltman3y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bnockles3z@so-net.ne.jp', 'Brier', 'Nockles', 'bnockles3z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sespinay40@auda.org.au', 'Sebastien', 'Espinay', 'sespinay40');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mgoodlake41@list-manage.com', 'Mort', 'Goodlake', 'mgoodlake41');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ahindhaugh42@mac.com', 'Agnola', 'Hindhaugh', 'ahindhaugh42');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ssola43@plala.or.jp', 'Stanislaw', 'Sola', 'ssola43');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ljedrys44@creativecommons.org', 'Lindsay', 'Jedrys', 'ljedrys44');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ltratton45@flickr.com', 'Lynnelle', 'Tratton', 'ltratton45');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cloadsman46@sun.com', 'Chad', 'Loadsman', 'cloadsman46');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'twooton47@businesswire.com', 'Tanney', 'Wooton', 'twooton47');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'atrustey48@ucoz.ru', 'Aindrea', 'Trustey', 'atrustey48');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ghadland49@irs.gov', 'Gordie', 'Hadland', 'ghadland49');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'jpoile4a@networkadvertising.org', 'Jorgan', 'Poile', 'jpoile4a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'alefrank4b@mapquest.com', 'Ashly', 'Le Frank', 'alefrank4b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cgrealish4c@reference.com', 'Cacilie', 'Grealish', 'cgrealish4c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dbere4d@xing.com', 'Daryl', 'Bere', 'dbere4d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mtorrance4e@economist.com', 'Maure', 'Torrance', 'mtorrance4e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sege4f@dagondesign.com', 'Sid', 'Ege', 'sege4f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'blister4g@disqus.com', 'Berk', 'Lister', 'blister4g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mquinby4h@google.com.br', 'Mellisa', 'Quinby', 'mquinby4h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'jottley4i@merriam-webster.com', 'Jarib', 'Ottley', 'jottley4i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vyoules4j@theatlantic.com', 'Valentine', 'Youles', 'vyoules4j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tmariet4k@comsenz.com', 'Theodosia', 'Mariet', 'tmariet4k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mswalwell4l@cbslocal.com', 'Marietta', 'Swalwell', 'mswalwell4l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ahobson4m@sciencedirect.com', 'Adara', 'Hobson', 'ahobson4m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hlukacs4n@earthlink.net', 'Hill', 'Lukacs', 'hlukacs4n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'emcgall4o@dailymotion.com', 'Emanuele', 'McGall', 'emcgall4o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rfusedale4p@histats.com', 'Rees', 'Fusedale', 'rfusedale4p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dplaskett4q@flickr.com', 'Daphne', 'Plaskett', 'dplaskett4q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'estorres4r@elegantthemes.com', 'Ellwood', 'Storres', 'estorres4r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pfrossell4s@ning.com', 'Phoebe', 'Frossell', 'pfrossell4s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bmcphail4t@businessweek.com', 'Bradly', 'McPhail', 'bmcphail4t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fcarlsson4u@slate.com', 'Fedora', 'Carlsson', 'fcarlsson4u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bdunlea4v@github.io', 'Barnie', 'Dunlea', 'bdunlea4v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ceby4w@google.es', 'Chloette', 'Eby', 'ceby4w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hmagnar4x@webs.com', 'Hale', 'Magnar', 'hmagnar4x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'follive4y@miitbeian.gov.cn', 'Frants', 'Ollive', 'follive4y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dbalthasar4z@vk.com', 'Durante', 'Balthasar', 'dbalthasar4z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fclarridge50@soundcloud.com', 'Fanni', 'Clarridge', 'fclarridge50');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kcarleton51@github.io', 'Karolina', 'Carleton', 'kcarleton51');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'palbrecht52@mapy.cz', 'Powell', 'Albrecht', 'palbrecht52');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lgawkes53@si.edu', 'Lutero', 'Gawkes', 'lgawkes53');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ssomerville54@prnewswire.com', 'Scotti', 'Somerville', 'ssomerville54');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vrudyard55@naver.com', 'Viola', 'Rudyard', 'vrudyard55');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gdoucette56@guardian.co.uk', 'Gerladina', 'Doucette', 'gdoucette56');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rlafflina57@mashable.com', 'Reinald', 'Lafflina', 'rlafflina57');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'amartschik58@alibaba.com', 'Alvira', 'Martschik', 'amartschik58');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kgoodlud59@ibm.com', 'Kit', 'Goodlud', 'kgoodlud59');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'herington5a@whitehouse.gov', 'Haroun', 'Erington', 'herington5a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mreeday5b@who.int', 'Maxi', 'Reeday', 'mreeday5b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'jsplain5c@shutterfly.com', 'Jerome', 'Splain', 'jsplain5c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cchristian5d@rediff.com', 'Christean', 'Christian', 'cchristian5d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cbrunner5e@umich.edu', 'Cassy', 'Brunner', 'cbrunner5e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'nmapplethorpe5f@vimeo.com', 'Norri', 'Mapplethorpe', 'nmapplethorpe5f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kgooble5g@bizjournals.com', 'Kristoforo', 'Gooble', 'kgooble5g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cferrario5h@blogger.com', 'Colver', 'Ferrario', 'cferrario5h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tpow5i@intel.com', 'Tamera', 'Pow', 'tpow5i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ipeeke5j@yellowpages.com', 'Ilsa', 'Peeke', 'ipeeke5j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rambroisin5k@yolasite.com', 'Rasla', 'Ambroisin', 'rambroisin5k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'opaunsford5l@issuu.com', 'Onofredo', 'Paunsford', 'opaunsford5l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dbarszczewski5m@plala.or.jp', 'Deeanne', 'Barszczewski', 'dbarszczewski5m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mrustman5n@constantcontact.com', 'Meir', 'Rustman', 'mrustman5n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'iwillows5o@tinyurl.com', 'Ingar', 'Willows', 'iwillows5o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cbosomworth5p@springer.com', 'Cristine', 'Bosomworth', 'cbosomworth5p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'egeerits5q@webnode.com', 'Etheline', 'Geerits', 'egeerits5q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'abaggot5r@addtoany.com', 'Almeda', 'Baggot', 'abaggot5r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dgarrit5s@webmd.com', 'Delilah', 'Garrit', 'dgarrit5s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'eeddisforth5t@adobe.com', 'Ermin', 'Eddisforth', 'eeddisforth5t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mepton5u@ca.gov', 'Marysa', 'Epton', 'mepton5u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ashulem5v@senate.gov', 'Ashlee', 'Shulem', 'ashulem5v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mfeatherby5w@yellowpages.com', 'Maressa', 'Featherby', 'mfeatherby5w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tokenden5x@mayoclinic.com', 'Tasha', 'Okenden', 'tokenden5x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sszapiro5y@wordpress.com', 'Sisile', 'Szapiro', 'sszapiro5y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sgregore5z@vk.com', 'Seward', 'Gregore', 'sgregore5z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gyewdall60@yellowbook.com', 'Grady', 'Yewdall', 'gyewdall60');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vgarnar61@usa.gov', 'Vite', 'Garnar', 'vgarnar61');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ggaylord62@bandcamp.com', 'Gregor', 'Gaylord', 'ggaylord62');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'respine63@csmonitor.com', 'Riordan', 'Espine', 'respine63');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gcoger64@seattletimes.com', 'Ginni', 'Coger', 'gcoger64');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'jhertwell65@cam.ac.uk', 'Jackie', 'Hertwell', 'jhertwell65');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kcredland66@furl.net', 'Karoly', 'Credland', 'kcredland66');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gcecchetelli67@salon.com', 'Gabbi', 'Cecchetelli', 'gcecchetelli67');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bsaye68@princeton.edu', 'Bobbi', 'Saye', 'bsaye68');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dbilles69@springer.com', 'Demetri', 'Billes', 'dbilles69');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gwelsh6a@ft.com', 'Graeme', 'Welsh', 'gwelsh6a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bsailor6b@tumblr.com', 'Bertrando', 'Sailor', 'bsailor6b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sdevas6c@about.com', 'Stillman', 'Devas', 'sdevas6c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rsenechell6d@yolasite.com', 'Rodge', 'Senechell', 'rsenechell6d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tixer6e@live.com', 'Tyson', 'Ixer', 'tixer6e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mmoxted6f@ning.com', 'Mufi', 'Moxted', 'mmoxted6f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gtattam6g@ebay.co.uk', 'Gabbey', 'Tattam', 'gtattam6g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mwootton6h@tinyurl.com', 'Maynard', 'Wootton', 'mwootton6h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rreach6i@reddit.com', 'Robina', 'Reach', 'rreach6i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ssims6j@un.org', 'Sutherlan', 'Sims', 'ssims6j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bsuddell6k@noaa.gov', 'Basil', 'Suddell', 'bsuddell6k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gboas6l@desdev.cn', 'Giffard', 'Boas', 'gboas6l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fbodle6m@dailymail.co.uk', 'Felipa', 'Bodle', 'fbodle6m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'njeremaes6n@wordpress.com', 'Natividad', 'Jeremaes', 'njeremaes6n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rsprakes6o@vk.com', 'Rudolph', 'Sprakes', 'rsprakes6o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rjillings6p@twitter.com', 'Rolando', 'Jillings', 'rjillings6p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'jpatron6q@wp.com', 'Jessamyn', 'Patron', 'jpatron6q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gfraser6r@disqus.com', 'Germaine', 'Fraser', 'gfraser6r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rkipping6s@hibu.com', 'Rachele', 'Kipping', 'rkipping6s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vclewley6t@indiatimes.com', 'Vonni', 'Clewley', 'vclewley6t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mdymocke6u@prnewswire.com', 'Mischa', 'Dymocke', 'mdymocke6u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cfiney6v@noaa.gov', 'Cathlene', 'Finey', 'cfiney6v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hdelafont6w@netvibes.com', 'Hillier', 'Delafont', 'hdelafont6w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tabbati6x@wufoo.com', 'Timothee', 'Abbati', 'tabbati6x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gnoone6y@sciencedaily.com', 'Gradey', 'Noone', 'gnoone6y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pmantione6z@canalblog.com', 'Paco', 'Mantione', 'pmantione6z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'xsmithin70@forbes.com', 'Xever', 'Smithin', 'xsmithin70');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rmaccaughan71@delicious.com', 'Reggi', 'MacCaughan', 'rmaccaughan71');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'nbristow72@wordpress.com', 'Natassia', 'Bristow', 'nbristow72');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lhansard73@tmall.com', 'Lilia', 'Hansard', 'lhansard73');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'awaison74@wisc.edu', 'Arie', 'Waison', 'awaison74');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lspring75@umn.edu', 'Liam', 'Spring', 'lspring75');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'plyngsted76@zimbio.com', 'Phil', 'Lyngsted', 'plyngsted76');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'wmuehler77@webmd.com', 'Wes', 'Muehler', 'wmuehler77');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'sgrinnikov78@netscape.com', 'Symon', 'Grinnikov', 'sgrinnikov78');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'creskelly79@nyu.edu', 'Carmon', 'Reskelly', 'creskelly79');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rchallenger7a@cnet.com', 'Rebecka', 'Challenger', 'rchallenger7a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'larchley7b@homestead.com', 'Laverne', 'Archley', 'larchley7b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'qcallingham7c@archive.org', 'Quincey', 'Callingham', 'qcallingham7c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lorwell7d@ebay.com', 'Loreen', 'Orwell', 'lorwell7d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rmcdonogh7e@ft.com', 'Rahel', 'McDonogh', 'rmcdonogh7e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'astallion7f@behance.net', 'Alis', 'Stallion', 'astallion7f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'phrinchishin7g@miibeian.gov.cn', 'Porty', 'Hrinchishin', 'phrinchishin7g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'nlies7h@wikia.com', 'Nert', 'Lies', 'nlies7h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cbesemer7i@chron.com', 'Cassi', 'Besemer', 'cbesemer7i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'bgyford7j@clickbank.net', 'Broderick', 'Gyford', 'bgyford7j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'wfurman7k@unc.edu', 'Wyatt', 'Furman', 'wfurman7k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'moflaherty7l@alexa.com', 'Megan', 'O''Flaherty', 'moflaherty7l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'earrault7m@tripod.com', 'Eric', 'Arrault', 'earrault7m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ooddey7n@msn.com', 'Osmond', 'Oddey', 'ooddey7n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'onelmes7o@auda.org.au', 'Orelia', 'Nelmes', 'onelmes7o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lpesek7p@deviantart.com', 'Lennie', 'Pesek', 'lpesek7p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ldelacour7q@homestead.com', 'Lela', 'Delacour', 'ldelacour7q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'achastney7r@tinyurl.com', 'Adora', 'Chastney', 'achastney7r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mhailston7s@sbwire.com', 'Mahala', 'Hailston', 'mhailston7s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mblinde7t@yellowpages.com', 'Milty', 'Blinde', 'mblinde7t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gwells7u@qq.com', 'Garret', 'Wells', 'gwells7u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'oogarmen7v@photobucket.com', 'Oralla', 'O''Garmen', 'oogarmen7v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'edailey7w@aol.com', 'Emmy', 'Dailey', 'edailey7w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'aseabridge7x@guardian.co.uk', 'Aron', 'Seabridge', 'aseabridge7x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mgallihaulk7y@eventbrite.com', 'Melitta', 'Gallihaulk', 'mgallihaulk7y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lbrum7z@liveinternet.ru', 'Laureen', 'Brum', 'lbrum7z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mharverson80@lycos.com', 'Miguela', 'Harverson', 'mharverson80');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lwoodyeare81@go.com', 'Leigha', 'Woodyeare', 'lwoodyeare81');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'evanyushkin82@delicious.com', 'Ebba', 'Vanyushkin', 'evanyushkin82');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pdye83@google.it', 'Piotr', 'Dye', 'pdye83');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lrichardes84@typepad.com', 'Lori', 'Richardes', 'lrichardes84');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'csnell85@dailymotion.com', 'Cristina', 'Snell', 'csnell85');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gfisbburne86@bluehost.com', 'Gilberto', 'Fisbburne', 'gfisbburne86');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hlevay87@latimes.com', 'Hanni', 'Levay', 'hlevay87');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lmabbot88@illinois.edu', 'Lynde', 'Mabbot', 'lmabbot88');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kragot89@phpbb.com', 'Kipper', 'Ragot', 'kragot89');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fsmoughton8a@ted.com', 'Fredi', 'Smoughton', 'fsmoughton8a');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hbambury8b@163.com', 'Heriberto', 'Bambury', 'hbambury8b');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hginnaly8c@icq.com', 'Hartley', 'Ginnaly', 'hginnaly8c');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'wvenus8d@sohu.com', 'Wylma', 'Venus', 'wvenus8d');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ldjekic8e@cisco.com', 'Lynelle', 'Djekic', 'ldjekic8e');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'rstormes8f@samsung.com', 'Rudy', 'Stormes', 'rstormes8f');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'lpietron8g@unesco.org', 'Lionel', 'Pietron', 'lpietron8g');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hmartinelli8h@thetimes.co.uk', 'Hodge', 'Martinelli', 'hmartinelli8h');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'aprisk8i@irs.gov', 'Ardelia', 'Prisk', 'aprisk8i');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'swindham8j@g.co', 'Sallie', 'Windham', 'swindham8j');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'zskinner8k@opensource.org', 'Zechariah', 'Skinner', 'zskinner8k');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'edreger8l@nps.gov', 'Ermanno', 'Dreger', 'edreger8l');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'awilliam8m@addtoany.com', 'Ada', 'William', 'awilliam8m');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kweare8n@g.co', 'Kellie', 'Weare', 'kweare8n');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ntolworthie8o@webnode.com', 'Nananne', 'Tolworthie', 'ntolworthie8o');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'cbore8p@geocities.com', 'Clement', 'Bore', 'cbore8p');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'dloach8q@edublogs.org', 'Donavon', 'Loach', 'dloach8q');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'hganford8r@hhs.gov', 'Hilton', 'Ganford', 'hganford8r');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'tjelphs8s@cafepress.com', 'Tybalt', 'Jelphs', 'tjelphs8s');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'pchidler8t@youtube.com', 'Peggie', 'Chidler', 'pchidler8t');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fshiels8u@statcounter.com', 'Franky', 'Shiels', 'fshiels8u');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'gjanton8v@themeforest.net', 'Giana', 'Janton', 'gjanton8v');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'civantsov8w@fema.gov', 'Carlyle', 'Ivantsov', 'civantsov8w');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'eratazzi8x@acquirethisname.com', 'Elinore', 'Ratazzi', 'eratazzi8x');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'mfarre8y@mysql.com', 'Mischa', 'Farre', 'mfarre8y');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'fredler8z@sciencedaily.com', 'Fredrick', 'Redler', 'fredler8z');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ccaslin90@globo.com', 'Carver', 'Caslin', 'ccaslin90');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'kkinloch91@tripod.com', 'Kaitlyn', 'Kinloch', 'kkinloch91');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'vlettsom92@google.it', 'Violante', 'Lettsom', 'vlettsom92');
INSERT INTO public.customer ( email, first_name, last_n... (744 KB left)